name: antrenman_app
description: "Antrenman Uygulaması"
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
    
